name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew
        
      - uses: actions/checkout@v4
      - name: Set up OpenJDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          
      - name: Build with Gradle
        run: ./gradlew build # Ensure your gradlew script is executable
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ExtendedCraftingTerminals-AE2
          path: build/libs/*.jar # Make sure this path matches the location of your build artifacts
